nodogsplash/nodogsplash

Makefile
libhttpd/api.c
src/conf.c
src/conf.h
src/gateway.c
src/httpd_thread.c
src/httpd_thread.h
src/util.c

This pull request should solve the problem of Issue #30.
I've just reverted the commit of Issue #9 without any conflict.
Then, solve the race conditions by turning static variables into local variables.

Turn nodogsplash back to multi-thread

---

debian/changelog

It is not a blocker for the upload to the distribution (like nothing in debian/* would be), just, I would not mind to see the ITP in the regular source tree.

Added ITP to prepare for Debian upload

---

src/httpd_thread.c

This segfault occures if: no daemon mode AND debuglevel 7 AND high load server with *httperf --hog --server=IP --port=2050 --wsess=100,10,0.01 --rate=100 --timeout=5* AND GDB not used.
This error fixed if *httpdEndRequest(r)* in *thread_httpd(void *args)* placed after debug message which use request *r->clientAddr*

fix segfault in httpd_thread.c under high load

---

src/ndsctl.c
src/ndsctl.h
src/ndsctl_thread.c
src/util.c
src/util.h

Sample output:
===================
```javascript
{
"client_length": 2,
"clients": {
"2f:82:71:b4:23:3f": {
"client_id": 0,
"ip": "10.10.10.115",
"mac": "2c:8a:72:b4:23:1f",
"added": 1464536854,
"active": 1464536854,
"duration": 107,
"token": "cc6cb718",
"state": "Preauthenticated",
"downloaded": "0",
"avg_down_speed": "0",
"uploaded": "0",
"avg_up_speed": "0"
},
"64:a8:50:da:eb:95": {
"client_id": 1,
"ip": "10.10.10.125",
"mac": "64:b8:53:da:eb:95",
"added": 1464536959,
"active": 1464536959,
"duration": 2,
"token": "3b45fdfb",
"state": "Preauthenticated",
"downloaded": "0",
"avg_down_speed": "0",
"uploaded": "0",
"avg_up_speed": "0"
}
}
}
```

Add 'ndsctl json' option

---

debian/control
debian/nodogsplash.service
debian/rules

Adds support to systemd systems (ie: debian jessie) and adds libmicrohttpd (>= 0.9.50) to package deps.
BTW: libmicrohttpd needs to be installed by tarbar or sid repository. The current version on stable repositories is lower then required version.

Debian systemd support

---

resources/infoskel.html

Often, a client will connect to NDS but not authenticate for a while. When they do, very often the token will have timed out and they are served up infoskel.html.
This is neither mobile or client friendly and leaves them in limbo.
Here is a new version with a button for them to continue. Tested on Apple, Windows, Android and various desktops/laptops.

Bluewavenet update infoskel.html

---

src/http_microhttpd.c
src/mimetypes.h

The segfault was due to the mimetype not being found by the lookup_mimetype method.
In the mimetypes.h the last entry was "NULL,NULL", causing a strcmp with a NULL value, which lead to a segfault.
I've removed the "NULL, NULL" entry in the mimetypes.h as it would segfault every time a mimetype wasn't found.
I also added font related mimetypes, wasn't mandatory but it's better to have them.

Fix segfault when mimetype isn't found (#216)

---

src/fw_iptables.c

Allow chaining to existing iptables rules for Trusted and Authenticated clients by changing from ACCEPT to RETURN in the NDS iptables settings. 
Tested on LEDE 170104. Also works for NDS version 1. See #229
Author-name: Rob White

Allow Chaining to Existing Firewall Rules

---

src/gateway.c

An extension to speed up the opening of successive Transmission Control Protocol (TCP) connections between two endpoint.
libmicrohttpd support [TCP Fast Open](https://en.wikipedia.org/wiki/TCP_Fast_Open) (Since 0.9.34)
nodogsplash use libmicrohttpd 0.9.51, so we can use this option to improve speed when get splash pages.
Thanks! :)

microhttpd: Use TCP Fastopen option

---

src/commandline.c
src/conf.c

This size make memory corruption.

conf.c: Fix strncpy memory leak

---

src/http_microhttpd.c

The recent removal of the "token" variable stopped the "$authtarget" directive from working. This fix renames "token" to "tok" in that directive.

Rename "token" to "tok"

---

docs/source/faq.rst
docs/source/fas.rst
docs/source/howitworks.rst
resources/nodogsplash.conf
src/conf.c
src/conf.h
src/fw_iptables.c
src/gateway.c
src/http_microhttpd.c

This implements redirection to an external authentication
service in place of splash.html.
It introduces four new options:
1. fasport - if set, enables FAS redirection and the value is
the port used for access.
2. fasremoteip - if set is the ip address of the FAS, defaults
to the NDS gateway address for the case of FAS running locally to NDS.
3. faspath - the path on FAS to the login page. Default "/"
4. fas_secure_enabled - if set to "1", the client token is not
revealed and it is the responsibility of the FAS to request
this from NDS. If set to "0", the client token is passed in
clear text in the query string to the FAS.
Firewall settings are automatically configured for access to the FAS.
Binauth can also be configured at the same time to allow a local
script to be called on …

Forward Authentication Service (FAS) Integration.

---

resources/nodogsplash.conf
src/http_microhttpd.c

Remove superfluous / character from FAS splashpageurl.
Update comment in .conf file to clarify.

Remove superfluous / character from FAS splashpageurl.

---

src/util.c

Show the configuration of both Binauth and FAS in the output of ndsctl status.

Add FAS and Binauth to ndsctl status

---

resources/splash.html
src/http_microhttpd.c

Indicate that the data is client specific.

rename uploadbytes/downloadbytes to clientupload/clientdownload

---

resources/splash.css
resources/splash.html
resources/status.html

Add hyphen to custom tag names in css
Move large comment section to after meta tag lines

Custom tag names - html 5.2 compliance

---

src/fw_iptables.c

Another step towards [IPv6 support](https://github.com/nodogsplash/nodogsplash/issues/38). nodogsplash already has some preliminary support for IPv6 in the current `master` code base. The fixes in this pull request solve the problems in `fw_iptables.c` causing nodogsplash immediately shutting down again due to errors in setting ip6tables rules.

IPv6 firewall fixes

---

Makefile
openwrt/nodogsplash/files/etc/config/nodogsplash
resources/nodogsplash.conf

Include in the package a fully functional login script for preauth.
Config file(s) are updated to include pre configured but commented out parameters to enable.
The login script generates dynamic html for NDS to serve using MHD. The login page asks for a username and email address. User logins are recorded in the file /tmp/ndslog.log
Differences between OpenWrt and Debian (and other Linux distributions) are taken into account.
Tested on OpenWrt Snapshot
`Signed-off-by: Rob White <rob@blue-wave.net>`

Include PreAuth Login script in package

---

debian/doc/nodogsplash.1
docs/source/faq.rst
docs/source/fas.rst
openwrt/nodogsplash/files/etc/config/nodogsplash
resources/nodogsplash.conf
src/conf.c

1. fasremoteip must be a dot format ipv4 address. The config value is now validated and NDS terminates with a console error message if validation fails.
2. Version 3.3.0 introduced improvements towards usable IPv6 support. This however induces a "too many redirects error" in device CPD if port 80 is used for FAS in the case of FAS running locally on the NDS device. Fasport is now checked for port 80 and local FAS, and NDS terminates with a console error message if these conditions are found.
3. The config file has been updated to reflect points 1 and 2.
4. Documentation has been updated to reflect points 1 and 2.
Compile tested on OpenWrt SDK, ath79 platform.
Run tested on gl-inet ar300m-16

 Validate Fasremoteip and Fasport 

---

openwrt/nodogsplash/files/etc/init.d/nodogsplash

The init script could parse the macmechanism and the mac lists, but it forgot to
add the macmechanism to the configuration itself

openwrt: initscript: add missing macmechanism in the config file

---

forward_authentication_service/PreAuth/demo-preauth-remote-image.sh

An example PreAuth login script that pulls an image from a remote server and displays it on the CPD browser screen.
This script is provided as a demonstration of how to display a remote image.
- The remote server can be https if required.
- The remote server IP address is not needed.

Add Preauth script that displays remote image

---

openwrt/nodogsplash/files/etc/init.d/nodogsplash
resources/nodogsplash.conf
resources/splash.html
resources/status.html
src/conf.c
src/conf.h
src/http_microhttpd.c

Both variables are not used anymore.
Iirc, the original purpose was to have explicit subfolders so to avoid path name clashes when the intercepted page was loaded. Otherwise, splash page content might be shown in the intercepted page.

remove unused pagesdir and imagesdir

---

src/commandline.c
src/conf.c
src/conf.h
src/debug.c
src/debug.h
src/ndsctl.c
src/ndsctl_thread.c

Make the debug level  platform independent and less confusing.
Now the levels are 0, 1, 2. We can add more if needed.
The default log level is 1.

make debuglevel platform independent

---

src/conf.c
src/ndsctl.c

Prevents deadlock on ndsctl and hangup of NDS if more than two instances of ndsctl are run concurrently.
Multiple instances may be run in the case of FAS with secure level 1. On a busy site probability of this happening is quite high resulting in apparently random failures requiring either a restart of NDS or a reboot.
This solution uses a lock file. The issue may be somewhere in mutex or epoll handling and would probably be better fixed there if that is the case, but this current work around seems reliable.
Now, with this fix, if a multiple concurrent instance of ndsctl finds the lock file present, it exits quietly with an error, logging to syslog.
If a crash was to leave the lock file present, a restart of NDS deletes the file.
A FAS using ndsctl to acquire the client token MUST check …

ndsctl: prevent deadlock with multiple concurrent instances

---

src/conf.c

ndsctl: clean up FILE pointer

---

debian/nodogsplash.service

Do not set debug level in nodogsplash.service
OS that use systemd eg Debian -
NDS will set the default to "1" or use the value set in nodogsplash.conf

Systemd: Do not set debug level in nodogsplash.service

---

resources/nodogsplash.conf
src/conf.c
src/http_microhttpd.c

redirectURL is now redundant as most CPD implementations immediately close the "splash" page
as soon as NDS authenticates, thus redirectURL will not be shown.
This functionality, ie displaying a particular web page as a final "Landing Page"
can be achieved reliably using FAS, with NDS calling the previous "redirectURL" as the FAS page.

Deprecate RedirectURL

---

docs/source/binauth.rst
docs/source/customize.rst
docs/source/howitworks.rst
forward_authentication_service/PreAuth/demo-preauth-remote-image.sh
forward_authentication_service/PreAuth/demo-preauth.sh
forward_authentication_service/binauth/binauth_log.sh
forward_authentication_service/binauth/binauth_sitewide.sh
forward_authentication_service/binauth/splash_sitewide.html
resources/splash.css
src/http_microhttpd.c
src/http_microhttpd_utils.c

This enhancement allows custom variables to be generated by FAS and to be sent to Binauth for action.
This is fully backward compatible with the current release (v4.0.2)
As this is a significant enhancement, the intention is to make a new release v4.1.0
FAS can embed custom variables into redir, allowing local post authentication processing to take place.
Two example scripts are provided for using binauth.
The first provides site-wide username/password login for two user groups, Staff and Guest in the example.
Staff has unlimited access, Guest is limited to 10 minutes per session.
The second provides local logging of NDS, particularly useful with a remote FAS.
The script suggests how a remote FAS can use BinAuth to set session durations on a client by client basis.
The documentation is …

BinAuth: Send redir variable to the binauth script

---

docs/source/binauth.rst
src/ndsctl.c

ndsctl: delete lock file if NDS is not started
docs: minor update

ndsctl: delete lock file if NDS is not started

---

docs/source/binauth.rst
docs/source/preauth.rst
forward_authentication_service/PreAuth/demo-preauth-remote-image.sh
forward_authentication_service/PreAuth/demo-preauth.sh
forward_authentication_service/binauth/binauth_log.sh
forward_authentication_service/binauth/binauth_sitewide.sh
src/http_microhttpd.c

* BinAuth - Send User Agent string and client-ip to the binauth script [bluewavenet]
* BinAuth - Update the two example BinAuth scripts showing use of passed arguments [bluewavenet]
* Documentation - Update BinAuth section [bluewavenet]
* PreAuth - Send User Agent string to the preauth script [bluewavenet]
* PreAuth - Update the example PreAuth script showing use of passed arguments [bluewavenet]
* Documentation - Update PreAuth section [bluewavenet]
Bump to version 4.2.0 as this adds significant functionality with backwards compatibility.

PreAuth and BinAuth: Pass user agent string to scripts.

---

src/main.c
src/util.c
src/util.h

NDS uptime may be from seconds to years (!!) too large if NTP client is
enabled when the system starts and there is no hardware RTC.
NDS started_time is deliberately left untouched, uptime discrepancy is
logged when debuglevel is >1 but uptime is correctly calculated.

fix: NDS uptime if NTP client enabled

---

forward_authentication_service/PreAuth/demo-preauth.sh
src/conf.c
src/conf.h
src/http_microhttpd.c
src/main.c
src/util.c
src/util.h

Enhances security and mitigates issues accessing ndsctl remotely to obtain the client token.
In addition, no additional packages are required allowing legacy low flash/ram devices to be used.
* For option fas_secure_enabled '1', NDS adds the hash of the client token (hid) to the query string.
* FAS concatenates hid and the fas key and hashes the result.
* This new hash is added to the query string returned to NDS instead of the client token.
* NDS then compares this hash with one it calculates itself from the client token and the pre-shared key.
For option fas_secure_enabled '2', the FAS can return either the client token in clear text
or can return the concatenated hash as for fas_secure_enabled '1', NDS will detect which is used.

FAS: Introduce hash_id mode.

---

README.md

Fix typo in project name in Readme#1-overview section

Fix typo in project name at Readme

---

openwrt/nodogsplash/files/usr/lib/nodogsplash/restart.sh
src/auth.c
src/auth.h
src/common.h
src/fw_iptables.c
src/http_microhttpd.c
src/ndsctl_thread.c

Fix a dead lock and a client list lock. [lynxis]
Fix: Memory corruption at high loads. [bluewavenet]
*  Symptom was spontaneous restart of NDS often with no errors.
*  Caused by coding error introduced by previous changes.
*  Added improved checking and debuglevel logging when calling MHD.
*  Added debuglevel logging for case of firewall restart.
*  Return error 403(forbidden) rather than 503(internal server error) when client attempts to use a forbidden http method.
*  Return error 403(forbidden) rather than 503(internal server error) when client attempts to use an invalid ip or mac address.
*  Revert QUERYMAXLEN to 4096 bytes to prevent query string truncation when a client session deauthenticates whilst client is using some types of vpn software.
Signed-off-by: Rob White …

Fix: restart at high loads, Fix: deadlock

---

forward_authentication_service/fas-aes/fas-aes.php

Fix final redirect in fas-aes.php
originurl needs to be url decoded

fas: fix final redirect in fas-aes.php

---

forward_authentication_service/libs/get_client_interface.sh

Script library to obtain the local wireless interface used by a client
Allows FAS, PreAuth and BinAuth to apply different conditions
depending on SSID used by client

fas: get-client-interface

---

forward_authentication_service/PreAuth/demo-preauth.sh

Variables, including user-defined, could have the characters ", " (comma space) included in them.
Previously variables would be truncated at the occurrence of the ", " as this is also the delimiter used by NDS. This change does improved delimiting checks to allow ", " to be used in variables.

PreAuth: Allow "comma space" (, ) to be used in variables

---

forward_authentication_service/libs/get_client_interface.sh

Extend get_client_interface:
Usage: get_client_interface [clientmac]
Returns: [local_interface] [meshnode_mac] [local_mesh_interface]
Where:
[local_interface] is the local interface the client is using.
[lmeshnode_mac] is the mac address of the 802.11s meshnode the client is using (null if mesh not present).
[local_mesh_interface] is the local 802.11s interface the client is using (null if mesh not present).

fas: Add mesh interface detection, syslog and command line help.

---

Makefile
forward_authentication_service/libs/get_client_interface.sh
openwrt/nodogsplash/Makefile
src/http_microhttpd.c
src/util.c
src/util.h

When option fas_secure_enabled '2' is set, get the client interface connections.
The client interface connections string is of the form:
[localif] [remotemeshnodemac] [localmeshif]
This is added to the query string as "clientif".
[remotemeshnodemac] and [localmeshif] will be null if  the client is connected
to a local interface or 802.11s mesh networking is not active.
This can be used to change the response of the FAS captive portal login page,
depending on the interface the client is connected to.
Connections to local wireless interfaces and
remote 802.11s mesh node connections are detected.

fas: get the client interface connections.

---

Makefile
forward_authentication_service/PreAuth/demo-preauth.sh
forward_authentication_service/libs/unescape.sh
openwrt/nodogsplash/Makefile
openwrt/nodogsplash/files/etc/config/nodogsplash
resources/nodogsplash.conf
src/http_microhttpd.c
src/http_microhttpd.h
src/main.c

This is a fix to allow "+" and "&" characters in user data passed to MHD in get requests.
Reported in issue #476, this effected PreAuth and Binauth.
"+" and "&" characters can now be used in form data, eg passwords etc.

Implement unescape callback for MHD (libmicrohttpd)

---

forward_authentication_service/PreAuth/demo-preauth-remote-image.sh
forward_authentication_service/PreAuth/demo-preauth.sh
forward_authentication_service/binauth/binauth_log.sh
forward_authentication_service/libs/get_client_interface.sh
forward_authentication_service/libs/get_client_token.sh
forward_authentication_service/libs/unescape.sh
openwrt/nodogsplash/files/etc/config/nodogsplash
openwrt/nodogsplash/files/etc/init.d/nodogsplash
resources/nodogsplash.conf
src/auth.c
src/conf.c
src/conf.h
src/http_microhttpd.c
src/http_microhttpd_utils.c
src/http_microhttpd_utils.h
src/main.c
src/ndsctl.c

This PR contains the following commits:
* Preauth: fix status authenticated - missing "=" and add utf-8 to the header
* Preauth: Support hashed id (hid) if sent by NDS; Fix status=authenticated
* Add shebang warning
* Add htmlentityencode function, encode gatewayname in templated splash page
* Add option: option unescape_callback_enabled
* PreAuth: htmlentity encode gatewayname on login page
* BinAuth: Prevent ndsctl from running if called from a Binauth script.
* Library scripts: Minor changes for better portability
* PreAuth and BinAuth: Add simple customisation of log file location.
The major enhancement is the addition of `option unescape_callback_enabled`
This defaults to disabled. When enabled, escaped query sting segments received from client CPD are sent to the external script …

4.4.1beta Enhancements and bug fixes

---

openwrt/nodogsplash/files/etc/config/nodogsplash
openwrt/nodogsplash/files/etc/init.d/nodogsplash
resources/nodogsplash.conf
src/conf.c
src/conf.h
src/main.c

See issue #515
MHD_get_version is used to determine the installed (runtime) version of
libmicrohttpd (MHD).
If the version is earlier than 0.9.69, then by default, NDS will terminate.
However, if option use_outdated_mhd is set to 1, NDS starts normally
but logs an error.

Add option use_outdated_mhd

---

forward_authentication_service/PreAuth/demo-preauth-remote-image.sh
forward_authentication_service/PreAuth/demo-preauth.sh
src/conf.c
src/conf.h
src/http_microhttpd.c
src/http_microhttpd_utils.c
src/main.c

This PR ensures Gatewayname is passed in the querystring in its urlencoded form.
In addition it expands htmlentity encoding to include & and +
Finally, included preauth scripts are modified to allow special characters in username.
- url-encode gatewayname on startup
- Add htmlentities "&" and "+"
- Preauth: Allow special characters in username

url-encode gatewayname on startup

---

forward_authentication_service/PreAuth/demo-preauth-remote-image.sh

At some stage, remote image retrieval stopped working in the demo preauth script.
This PR fixes the problem

PreAuth: Fix broken remote image retrieval

---

forward_authentication_service/PreAuth/demo-preauth-remote-image.sh
forward_authentication_service/PreAuth/demo-preauth.sh
openwrt/nodogsplash/files/etc/config/nodogsplash
resources/nodogsplash.conf
src/conf.c
src/main.c

See issue #516
"#" is used as a comment indicator in nodogsplash.conf
This fix allows the character to be present as part of an option value.
If the character occurs at the beginning of the line,
the line will be considered as a comment.
"'" (single quote/asterisk) is used as a uci delimiter.
If this character is required in gatewayname then use the
htmlentity &#39; instead.
The default config files have been updated to reflect this.
The demo preauth scripts have been modified to ensure
gatewayname is properly escaped.

Fix: Allow use of "#" and "'" (single quote/asterisk) in gatewayname

---

openwrt/nodogsplash/files/etc/config/nodogsplash
resources/nodogsplash.conf
src/util.c

ndsctl: add trusted devices list to json output.
The ndsctl json command now counts the number of trusted devices and outputs a list of them in json array format.
Some minor typos are also fixed in the config files.

ndsctl: add trusted devices list to json output.

---

Makefile

FAS was removed but it wasn't removed on Makefile 
forward_authentication_service directory doesn't exist #568

FAS removal on Makefile

---

src/http_microhttpd.c

Fix a buffer overflow for long queries.
Script to trigger
```python
#!/usr/bin/env python3
import socket 
CAPTIVE_IP = '192.168.99.3'
CAPTIVE_PORT = 2050
overflow = 'A'*30000
r = f'GET /?host=kek{overflow} HTTP/1.1\nHost: localhost\n\n'
sock = None
try:
sock = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
sock.connect((CAPTIVE_IP, CAPTIVE_PORT))
sock.send(r.encode())
finally:
if sock != None:
sock.close()
````

Fix buffer overflow
