- Makefile
- debian/changelog
- debian/control
- debian/doc/nodogsplash.1
- debian/links
- debian/rules
Debian packaging is lintian clean. Diverse improvements throughout.
> Improved Debian packaging

- libhttpd/api.c
- src/commandline.c
- src/conf.c
- src/conf.h
- src/fw_iptables.c
- src/gateway.c
- src/util.c
A first step in the direction of IPv6 support.
> stub ipv6 support

- src/util.c
The travis auto-builds had complained.
> executed make fixstyle to help auto-builds

- docs/source/checkinterval.rst
- src/conf.c
Signed-off-by: Philipp Deppenwiese <zaolin@das-labor.org>
> Fix CheckInterval option

- src/client_list.c
- src/firewall.c
> Remove allocation

- docs/source/compile.rst
Just made it a bit readable :)
> Fixing text errors

- src/gateway.c
version checking after microhttpd.h including
> gateway.c: check for libmicrohttp version fix

- ChangeLog
- docs/source/binauth.rst
- resources/nodogsplash.conf
- src/client_list.c
- src/conf.c
- src/conf.h
- src/http_microhttpd.c
- src/util.c
Reintroduces a setting clienttimeout to set the session duration of an authenticated client.
> add setting sessiontimeout

- .travis.yml
we need to wait for https://github.com/travis-ci/apt-package-whitelist/issues/3660
> Travis docs

- docs/source/binauth.rst
Adds paragraph describing manual_auth ack
> Add Binauth acknowledge

- src/debug.c
- src/ndsctl.c
- src/ndsctl.h
- src/ndsctl_thread.c
- src/util.c
- src/util.h
Allows "ndsctl json [ip|mac|token]".
Untested so far.
> Json filter

- resources/splash.html
- resources/status.html
Make status.html say something meaningful.
Tidy up splash.html a bit
> Update splash.html and status.html

- debian/doc/nodogsplash.1
- docs/source/ndsctl.rst
> Documentation update for version 3.1.0

- docs/source/fas.rst
- forward_authentication_service/FAS-Docs/readme
Final update FAS docs for v3.2.0 including:
"Using the simple example files"
> Uppdate FAS documentation for V3.2.0

- src/http_microhttpd.c
- src/template.c
- src/template.h
Some code simplifications for the template engine.
> simplify templater

- Makefile
- resources/splash.css
- resources/splash.html
- resources/status.html
Add splash.css file, update splash and status html
Update comments embedded in splash.html.
> Add splash.css file, update splash and status html

- docs/source/fas.rst
> FAS documentation update

- src/auth.c
- src/client_list.c
- src/client_list.h
- src/fw_iptables.c
- src/util.c
> Fix counter reset

- docs/source/index.rst
- docs/source/traffic.rst
> Add documentation for SQM scripts

- docs/source/traffic.rst
> Documentation: Readthedocs requires Pygments lexers on codeblocks so add them

- src/fw_iptables.c
- src/http_microhttpd.c
- src/util.c
see issue https://github.com/nodogsplash/nodogsplash/issues/38#issuecomment-437966493 (IPv6 support)
> IPv6 address length fixes

- openwrt/README.md
- openwrt/nodogsplash/Makefile
- openwrt/nodogsplash/files/etc/config/nodogsplash
- openwrt/nodogsplash/files/etc/init.d/nodogsplash
- openwrt/nodogsplash/files/etc/uci-defaults/40_nodogsplash
- openwrt/nodogsplash/files/usr/lib/nodogsplash/restart.sh
- openwrt/readme
@bluewavenet is this what you meant?
Code is sometimes easier than words. :->
> keep openwrt package files in nds repository

- openwrt/nodogsplash/files/etc/init.d/nodogsplash
> Add preauth to init.d

- openwrt/nodogsplash/files/etc/config/nodogsplash
- openwrt/nodogsplash/files/etc/init.d/nodogsplash
@bluewavenet can you take a look. In case I missed something. The network setting has been removed und essentially merge with gatewayinterface.
> remove dead code for removed network setting

- src/http_microhttpd.c
When FAS is enabled, returns "Error 403 Forbidden" if http://gw_address:gw_port is accessed directly (rather than being triggered by CPD or trying to access a port 80 web site). 
> Prevent access to the basic splash page (splash.html) when FAS is enabled.

- debian/doc/nodogsplash.1
- docs/source/preauth.rst
Updated for both readthedocs and man page
> Update PreAuth Documentation

- forward_authentication_service/PreAuth/demo-preauth.sh
- resources/splash.css
- resources/splash.html
- resources/status.html
Improve splash.css and tidy up splash/status.html and Preauth demo script.
`Signed-off-by: Rob White <rob@blue-wave.net>`
> Improve splash.css

- openwrt/nodogsplash/Makefile
For OpenWrt MakeFile
`Signed-off-by: Rob White <rob@blue-wave.net>`
> Install default Preauth login script

- src/conf.c
- src/util.c
- src/util.h
A less error prone method to check for a valid ip address.
> use elegant check for valid ip addresses

- debian/changelog
- debian/doc/nodogsplash.1
- docs/source/fas.rst
- docs/source/install.rst
- docs/source/overview.rst
- docs/source/todo.rst
- notes/release_todos
- openwrt/nodogsplash/files/etc/config/nodogsplash
> Version 4.0.0 release preparation

- docs/source/conf.py
> Add short title to navigation bar (readthedocs)

- src/fw_iptables.c
- src/main.c
Put some fas code behind `if (config->fas_port)`.
> put fas code into block

- forward_authentication_service/fas-aes/fas-aes.php
NDS successfully authenticated the client but resulted in NDS failing to finally redirect to the originally requested URL producing a 404 error.
> Fix coding error in fas-aes.php incorrectly passing redir back to NDS

- openwrt/nodogsplash/files/etc/init.d/nodogsplash
- src/main.c
Write log to SYSLOG. Make debuglevel 0 silent except for LOG_ERR
> Write log to SYSLOG. Make debuglevel 0 silent except for LOG_ERR

- src/ndsctl_thread.c
errno is a positive error code
> thread_ndsctl: check for positive errno

- README.md
- docs/source/overview.rst
> docs: Overview update

- src/main.c
> faskey: exit gracefully if not set and fas_secure_enabled =2

- forward_authentication_service/fas-hid/fas-hid.php
- src/http_microhttpd.c
Create fas-hid.php, update fas-aes.php and add missing gateway address.
> Create fas-hid example script and add missing gateway address.

- docs/source/fas.rst
- forward_authentication_service/fas-aes/fas-aes.php
- forward_authentication_service/fas-hid/fas-hid.php
- src/common.h
- src/http_microhttpd.c
Reduce memory requirements and fix log file location.
Update documentation.
> Reduce memory, fix log file location, docs update

- docs/source/faq.rst
- docs/source/fas.rst
- docs/source/howitworks.rst
> Documentation updates for v4.3.0

- forward_authentication_service/PreAuth/demo-preauth-remote-image.sh
- forward_authentication_service/PreAuth/demo-preauth.sh
The log file created by the default PreAuth script is stored on /tmp
This is usually a dynamic ram disk with limited capacity, so it is essential to ensure the log file does not grow too big as it will starve the system of not only /tmp storage capacity but also free ram, particularly on legacy systems with small ram.
This enhancement limits the log file size and writes an error message to syslog if the maximum size is reached.
The maximum size is defined as a proportion of the available free space.
The log file location can be changed with a simple edit, as can the maximum size proportion.
> PreAuth: Limit log size and write to syslog

- forward_authentication_service/binauth/binauth_log.sh
The log file created by the example BinAuth script, binauth_log.sh, is stored on /tmp
This is usually a dynamic ram disk with limited capacity, so it is essential to ensure the log file does not grow too big as it will starve the system of not only /tmp storage capacity but also free ram, particularly on legacy systems with small ram.
This enhancement limits the log file size and writes an error message to syslog if the maximum size is reached.
The maximum size is defined as a proportion of the available free space.
The log file location can be changed with a simple edit, as can the maximum size proportion.
> BinAuth: Limit log size and write to syslog

- debian/changelog
- See https://github.com/nodogsplash/nodogsplash/issues/447#issuecomment-540098767.
> Fix deb package build error

- src/auth.c
- src/auth.h
- src/fw_iptables.c
- src/ndsctl_thread.c
Fix a dead lock and a client list lock.
Please let me merge this (by cherry-picking it to the master)
> locking issues

- forward_authentication_service/PreAuth/demo-preauth-remote-image.sh
Add notice of dependencies for retrieving remote image using https
Add image type (jpg, png etc)
> Specify requirements for retrieving https remote image

- forward_authentication_service/PreAuth/demo-preauth-remote-image.sh
- forward_authentication_service/PreAuth/demo-preauth.sh
- forward_authentication_service/libs/get_client_interface.sh
- resources/splash.css
> Preauth: update login and demo-preauth scripts to display client zone

- forward_authentication_service/PreAuth/demo-preauth-remote-image.sh
- forward_authentication_service/fas-aes/fas-aes.php
> fas and preauth updates

- docs/source/fas.rst
- docs/source/index.rst
- docs/source/libraries.rst
- forward_authentication_service/PreAuth/demo-preauth-remote-image.sh
- forward_authentication_service/PreAuth/demo-preauth.sh
- forward_authentication_service/fas-aes/fas-aes.php
- forward_authentication_service/libs/get_client_interface.sh
- forward_authentication_service/libs/unescape.sh
- openwrt/nodogsplash/files/etc/config/nodogsplash
- openwrt/nodogsplash/files/usr/lib/nodogsplash/restart.sh
- resources/nodogsplash.conf
Numerous fixes and tidyups.
Documentation updates
Preparing for 4.4.0 release
> Preparing for 4.4.0 release

- Makefile
- docs/source/fas.rst
- forward_authentication_service/libs/get_client_token.sh
- openwrt/nodogsplash/Makefile
> Add get_client_token library utility

- docs/source/libraries.rst
> Documentation for get_client_token

- forward_authentication_service/PreAuth/demo-preauth-remote-image.sh
- forward_authentication_service/PreAuth/demo-preauth.sh
- forward_authentication_service/libs/get_client_interface.sh
- forward_authentication_service/libs/get_client_token.sh
- src/main.c
> Add missing NULL parameter and fix script failures

- forward_authentication_service/fas-aes/fas-aes.php
- src/conf.c
- src/conf.h
- src/http_microhttpd.c
- src/http_microhttpd_utils.c
- src/main.c
- Htmlencode gatewayname at startup for correct display on templated splash page
- Some minor cosmetic fixes
- Remove unused constant, multiple cosmetic improvements
- FAS: Prevent php notices on pedantic php servers
> Htmlencode gatewayname at startup and cosmetic updates

- src/main.c
> Tidy up main_loop, removing namespace pollution

- src/auth.c
- src/client_list.c
- src/conf.c
- src/fw_iptables.c
- src/http_microhttpd.c
- src/http_microhttpd_utils.c
- src/main.c
- src/ndsctl.c
- src/ndsctl_thread.c
- src/safe.c
- src/template.c
- src/util.c
> Coding style update - use // for single line comments

- debian/control
> Remove useless dependency

- debian/changelog
> Update debian changelog

- docs/source/customize.rst
> [Typo] Fix typo in docs/customize.rst
